# Generated by Django 4.2.4 on 2023-09-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.TextField(),
        ),
    ]
